name: Lint

on:
  push:
  pull_request:
    type: [ "opened", "reopened", "synchronize" ]

env:
  FORCE_COLOR: 1

jobs:
  build:
    name: pre-commit
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v7

      - name: Set up Python
        uses: actions/setup-python@v7
        with:
          python-version: '3.x'

      - name: Install uv
        uses: astral-sh/setup-uv@v7
        with:
          enable-cache: true
          cache-dependency-glob: uv.lock

      - name: Install dependencies
        run: uv sync --locked --group lint

      - name: Lint
        run: |
          uv run --group lint pre-commit run --all-files --show-diff-on-failure
        env:
          PRE_COMMIT_COLOR: always
