name: Test

on:
  push:
  pull_request:
    type: [ "opened", "reopened", "synchronize" ]
  schedule:
    - cron: '0 12 * * 0'  # run once a week on Sunday
  # Allows running this workflow manually from the Actions tab
  workflow_dispatch:

env:
  FORCE_COLOR: 1

jobs:
  tests:
    name: py-${{ matrix.python-version }}:pytest-${{ matrix.pytest-version }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: [
          "3.10",
          "3.11",
          "3.12",
          "3.13",
          "3.14",
          "pypy-3.11",
        ]
        pytest-version: [
          "8.2.*",
          "8.3.*",
          "8.4.*",
          "9.0.*",
          "9.1.*",
          "main",
        ]
    steps:
      - uses: actions/checkout@v7

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v7
        with:
          python-version: ${{ matrix.python-version }}
          allow-prereleases: true

      - name: Install uv
        uses: astral-sh/setup-uv@v7
        with:
          enable-cache: true
          cache-dependency-glob: uv.lock

      - name: Install dependencies
        run: uv sync --locked --group test

      - name: Tests
        shell: bash
        run: |
          if [[ '${{ matrix.pytest-version }}' == 'main' ]]; then
            uv run --group test --with "pytest @ git+https://github.com/pytest-dev/pytest.git@56a92c19d4a71152c594726efc9deb5f0e126e99" pytest
          else
            uv run --group test --with "pytest==${{ matrix.pytest-version }}" pytest
          fi

  platform:
    # Test devel setup on different platforms.
    name: Platform-${{ matrix.os }}
    needs: [ tests ]
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    steps:
      - name: Checkout
        uses: actions/checkout@v7

      - name: Setup Python
        uses: actions/setup-python@v7
        with:
          python-version: '3.x'
          architecture: 'x64'

      - name: Install uv
        uses: astral-sh/setup-uv@v7
        with:
          enable-cache: true
          cache-dependency-glob: uv.lock

      - name: Development setup on platform ${{ matrix.os }}
        run: |
          uv sync --locked --group test

      - name: Tests
        run: uv run pytest tests/
